on: 
  pull_request:
    branches:
      - '**'

jobs:
  install-sprkl-test:
    runs-on: ubuntu-latest
    name: Installing Sprkl Testing
    steps:

      - uses: actions/checkout@v3


      - name: Sprkl Setup
        uses: sprkl-dev/sprkl-action/setup@add-dashboard-push-support
        with:
          analyze: true
          token: ${{ secrets.SPRKL_CI_TOKEN }}

      - run: yarn install
      - run: yarn test:e2e:sprkl
        env: 
          SPRKL_RECIPE: all
