on: 
  push:
    branches:
      - '**'
jobs:
  install-sprkl-test:
    runs-on: ubuntu-latest
    name: Installing Sprkl Testing
    steps:

      - uses: actions/checkout@v3

      - name: Sprkl Setup
        uses: sprkl-dev/sprkl-action/setup@master
        with:
          analyze: false
          token: ${{ secrets.SPRKL_CI_TOKEN }}

      - run: yarn install
      - run: yarn test:e2e:sprkl
