on:
  pull_request_review:
    types: [submitted, edited]
jobs:
  install-sprkl-test:
    runs-on: ubuntu-latest
    name: Installing Sprkl Testing
    steps:

      - uses: actions/checkout@v3


      - name: Sprkl Setup
        uses: sprkl-dev/sprkl-action/setup@512127b9d22177b5fa2e52f77c4032668efc669b
        with:
          analyze: false
          token: ${{ secrets.SPRKL_CI_TOKEN }}

      - run: echo $SPRKL_RECIPE
      - run: echo $SPRKL_COMMITS

      - run: yarn install
      - run: yarn test:e2e:sprkl

      
