on: 
  push:
    branches:
      - '**'
jobs:
  install-sprkl-test:
    runs-on: ubuntu-latest
    name: Installing Sprkl Testing
    steps:

      - uses: actions/checkout@v3


      - name: Sprkl Setup
        uses: sprkl-dev/sprkl-action/setup@53120a36752d28f686d7b7d45368aaac5cb78250
        with:
          setenv: true
          analyze: true
          token: ${{ secrets.SPRKL_CI_TOKEN }}

      - run: yarn install
      - run: yarn test:e2e:sprkl

      
