on: 
  push:
    branches:
      - '**'
jobs:
  install-sprkl-test:
    runs-on: ubuntu-latest
    name: Installing Sprkl Testing
    steps:

      - uses: actions/checkout@v3


      - name: Sprkl Setup and Post Push
        uses: sprkl-dev/sprkl-action/setup@3b23824d79f9694660633ea7f969fc73bcb51da4
        with:
          setenv: true
          analyze: true
          token: ${{ secrets.SPRKL_CI_TOKEN }}
        env:
          SPRKL_LOG_LEVEL: debug

      - run: echo $NODE_OPTIONS

      - run: yarn install
      - run: yarn test:e2e:sprkl

      
