on: 
  push:
    branches:
      - '**'
jobs:
  install-sprkl-test:
    runs-on: ubuntu-latest
    name: Installing Sprkl Testing
    steps:

      - uses: actions/checkout@v3


      - name: Sprkl Setup
        uses: sprkl-dev/sprkl-action/setup@10349f03f3e7501974d2ee5961ab1df5e21dd23b
        with:
          analyze: true
          token: ${{ secrets.SPRKL_CI_TOKEN }}

      - run: yarn install
      - run: yarn test:e2e:sprkl

      
