on:
  pull_request:
    types: [opened, reopened]
jobs:
  install-sprkl-test:
    runs-on: ubuntu-latest
    name: Installing Sprkl Testing
    steps:

      - uses: actions/checkout@v3


      - name: Sprkl Setup
        uses: sprkl-dev/sprkl-action/setup@handle-workflows-events
        with:
          analyze: true
          token: ${{ secrets.SPRKL_CI_TOKEN }}

      - run: echo $SPRKL_RECIPE
      - run: echo $SPRKL_COMMITS

      - run: yarn install
      - run: yarn test:e2e:sprkl

      
