on:
  pull_request:
    types: [opened, reopened]
jobs:
  install-sprkl-test:
    runs-on: ubuntu-latest
    name: Installing Sprkl Testing
    steps:

      - uses: actions/checkout@v3


      - name: Sprkl Setup
        uses: sprkl-dev/sprkl-action/setup@ff96a4524d01d5b526c89369ca7c8bb230c6dafa
        with:
          analyze: true
          token: ${{ secrets.SPRKL_CI_TOKEN }}

      - run: yarn install
      - run: yarn test:e2e:sprkl

      
